# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://conperis.de
title: Conperis GmbH
email: mail@conperis.de
author: Christian Decker
description: > # "Write an awesome description for your new site here. 
  analytics startup for data quality in TINI Systems
copyright: 'Copyright &copy; 2017 Christian Decker. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/conperis
  - title: github
    url: https://github.com/conperis
  - title: linkedin
    url: 
