# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://conperis.de
title: Conperis GmbH
email: mail@conperis.de
author: Christian Decker
description: > # "Write an awesome description for your new site here. 
  analytics startup for data quality in TINI systems
copyright: 'Copyright &copy; 2017 Conperis GmbH. All Rights Reserved.'
credits: 'Disclaimer: Experimental page. Conperis is not in business.'
# credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: mail
    icon: envelope
    url: mailto:mail@conperis.de
  - title: twitter
    icon: twitter
    url: https://twitter.com/conperis
  - title: linkedin
    icon: linkedin
    url: 
  - title: github
    icon: github
    url: https://github.com/conperis
  
